### ISSUE TITLE
Cached (Beta) when enabled incredibly slow. 

### ISSUE THREAD

**Issue by Tinuz97** [Tempest0580/tempest#32]
Hi, long time that I reported something.
I have no idea how to log this, but I know when this problem happened for me. 

First:
If I turn the cached option off, it scrapes incredibly fast (like +- 20 seconds, and ready) 

If I turn the option on, I can wait like 3-5 minutes, this issue (well for me) started when you changed the cfscrape importing, the first time you introduced that in the changelog.

With the 'old' import style,and cached torrents enabled, it was (for me) just as fast as i turned the option off. 

Wiped every cache option that is available for Tempest, removed tempest in the userdata folder (to start realy clean), but the isssue  persist. 

Thx 🙂

**Comment by Tempest0580** [comment]
Yes I have noticed this as well. I'm going to test it and most likely going to swap it back in the next update.  Hopefully I can test it and push the update tomorrow.  

I'm also testing a way to check all the non torrent debrid files as well like the cached torrent it will should remove all the dead links. 

Working on a way to test the rest of the links as well. Hopefully to remove all dead links completely. 

Thanks

**Comment by Tinuz97** [comment]
Almost forgot, I think BTDB scraper is broken, I noticed (I think) they changed the website (looks different then before).

No need to hurry, I just leave cached off for now 🙂

**Comment by marson53** [comment]
BTDB Has changed to https://btdb.io/

**Comment by Tinuz97** [comment]
Yes, but also the search function, only changing to io (in the scraper) does not fix it (already tryed that).
The self.search if different also I guess.

**Comment by Tempest0580** [comment]
Pushed a Update that should fix Cached torrent check slowing down, Added Non Torrent check (Testing at this point).
Fixed BTDB scraper as well.

Thanks

**Comment by Tinuz97** [comment]
Testing in a minute, thx for the fix(es) 👍

**Comment by Tempest0580** [comment]
No problem.  If you can test the non torrent check also. The setting is in the debrid providers. It may need more work tho.

**Comment by Tinuz97** [comment]
Much better, but still very slow of it is at number 13 (counting down scrapers), keeps hanging at 12.
(jojo rabit movie) 

After the hang at 12 it shows the links, but many torrent scrapers missing. 

If I disable the cache check again, scraping goes fast, and shows all scrapers at the results again. 
Wiped all cache options, but unfortunately it does not fix it for me.

Any option for logging this?

**Comment by Tempest0580** [comment]
What device are you running kodi on?

**Comment by Tinuz97** [comment]
Version 5.0.35, almost forgot that.

**Comment by Tinuz97** [comment]
At the moment I tested it on my windows computer, windows 10,kodi 18.5.

**Comment by Tempest0580** [comment]
Wait for version 5.0.36. It hasn't updated on your end yet

**Comment by Tempest0580** [comment]
I know on my linux pc it runs alot faster. But on my fire sticks it hangs on a few scrapers. Haven't figured out how to speed it up yet on the android devices.

**Comment by Tinuz97** [comment]
I have no idea why it is so slow,also missing allot of scraper results, maybey the ones are missing causing the slow down it it reaches them while searching for links?

Version 5.0.36, wipes all cache options. 

Fen with cached enabled is ready in +- 20-30 seconds (including showing the results)

I7 3770k at 4.0ghz
8gb ram
Samsung 830 pro ssd. 



Video

https://tinuz97.stackstorage.com/s/NM53NDRMBSjvlN2

**Comment by Tempest0580** [comment]
Ok I'll do some more research.  I know Fen uses a different cache check then I do. Not sure if/what scrapers Fen uses though.  

My way tests the links as it scrapes the sources. I think Fen scrapes the sources then checks them.

**Comment by Tempest0580** [comment]
In that video did you have the non torrent debrid check on as well?
Cause that will cause all the scrapers to slow down even more.

**Comment by Tinuz97** [comment]
Fen uses (I think) some sort of cache file check, because it uses a separate auth (and client) for cache checks (of you enable cache check in Fen, you also must authorize Fen for it, not only ResolveUrl), same idea as Seren and Gaia I guess, but just a guess.

**Comment by Tinuz97** [comment]
No, only torrent cache check enabled 🙂

**Comment by Tempest0580** [comment]
Ok I'll do some more research and try to improve on the scrapers and the cache check and see if I can speed things up.

**Comment by Tinuz97** [comment]
The Oath (no idea how he using cache check) is blazing fast also with cache check enabled, maybey a idea to look at it and get a idea?

**Comment by Tinuz97** [comment]
![IMG_20200225_022353__01](https://user-images.githubusercontent.com/47715606/75206115-f4519980-5775-11ea-963a-47201fc5497b.jpg)
Ah, that is why It is fast I guess, modified Fen cache check code 🙂

**Comment by Tempest0580** [comment]
I'm pretty sure it adapted his from fen. I'll probably use his work and see if it makes a difference in tempest.  

Well you see yourself. Lol

**Comment by Tinuz97** [comment]
But, the first release from you, or 2nd, was just as fast (just fyi).

**Comment by Tempest0580** [comment]
I'll look into using his way. If it is better I'll possibly push it in the next day of two.

**Comment by Tempest0580** [comment]
Maybe I'll go back and see what I may have changed and see if I can fix it. To be honest I like doing my own without have to steal from others.

**Comment by Tinuz97** [comment]
I know that 😄
To bad I forgot which version did work perfectly (cached working, and fast scraping). 

I think it was the first, 2nd or 3th release.

**Comment by Tempest0580** [comment]
Ok I'm going to push 1 more update tonight in a few mins. I added some code in I was testing and pushed it in a update. I didnt mean to push it though.  Lol

**Comment by Tinuz97** [comment]
Going to bed (02:30 in the netherlands), so I will test in a few hours.

Good night 🙂

**Comment by Tempest0580** [comment]
Ok pushed the last update for the night. Let me know if that makes a difference.  I reverted some code back to when I first pushed a updated with cached torrents.  Seems to been running fast again to me.

**Comment by Tinuz97** [comment]
Yes, perfect now, like the first time (cached enabled for torrents) 🎉👍👌

**Comment by Tempest0580** [comment]
That's great. If you feel up to it test the debrid check for me. And let me know your thoughts on how it runs with it. It will scrape slower but it should remove the dead links as well.

Thanks

**Comment by Tinuz97** [comment]
Working also, I think (because there is no cached, or checked txt for debrid hosters).
Indeed slower, but not that bad like before the fix 🙂

**Comment by Tempest0580** [comment]
Great. In the next update I'll make it so it shows its cached/checked. 

Thanks

**Comment by Tempest0580** [comment]
Pushed a update. Rewrote a couple scrapers and the way the cached torrents and rd checker was. Should make it slightly faster now.

**Comment by Tinuz97** [comment]
Yes, before it was.l good also (after the fix), but now it is even faster, works great :)

**Comment by Tempest0580** [comment]
That's great.
Thanks

**Comment by Tinuz97** [comment]
I noticed something else, nothing to do with this issue (that is wonderfully fixed), but I don't wanna spam support tickets.

The new 'crazysourcehd' does work beautifully for movies, but for TV shows somehow I get wrong episode numbers (try Arrow, season 8, episode 10 as a example).
Not a big problem, because there are plenty of other sources to choose from (I always use torrents), but I just wanted to 'report' it :)

**Comment by Tempest0580** [comment]
Ok I'll check it out. See if it's the site or if I need to tweak the scraper some. 
I'm also trying to weed out any crap scrapers. To help speed things up. Honestly we only need one good link that works. But should have a couple for backups and a couple for people to choose if they like.

**Comment by Tinuz97** [comment]
That brings me to a idea, but no idea if possible.
Let's say if you want debrid only scrapers, (correct me if I am wrong), if you enable that, it is still searching the free, and none debrid ones, right?

Would be cool if you did have a switch, that realy disable the none debrid ones (if the switch is on), that would increase scraping time even more (I guess), I think the majority is using a debrid service these days (not all), so a switch that realy disables the free ones would be cool :)

**Comment by Tempest0580** [comment]
I might be able to do something. let me see what i can do.
